name: flutter_payments
author: Delightful Goods, Inc. <hello@delightfulgoods.co>
homepage: https://github.com/pplante/flutter_payments
description: In App Payments for Apple and Google Play, supporting all forms of IAP products.
version: 0.1.5

environment:
  sdk: ">=2.0.0-dev.28.0 <3.0.0"
  flutter: ">=0.2.4 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  url_launcher: "^5.0.2"

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: "^4.0.0"

flutter:
  plugin:
    androidPackage: co.delightfulgoods.flutterpayments
    pluginClass: FlutterPaymentsPlugin
